version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.44
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test1:1:3,test2:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  composer:
    image: composer
    container_name: kafka-composer
    working_dir: /data
    volumes:
      - ./data:/data/
  php:
    build: ./docker/php
    container_name: kafka-php
    working_dir: /data/src
    volumes:
      - ./data:/data/